### ISSUE TITLE
Dracula theme

### ISSUE THREAD

**Issue by poperigby** [SimpleMobileTools/General-Discussion#105]
Since some of the colors are limited to presets, it's impossible for me to make my own [Dracula Theme](https://draculatheme.com/). Can you add it as one of the default themes?

**Comment by tibbi** [comment]
well premade themes consist of those colors too. What text/background/primary color should it have?

**Comment by PopeRigby** [comment]
Text: #8be9fd
Background: #282a36
Primary: #44475a

**Comment by SebiderSushi** [comment]
Come to think of it, why did the "Primary color" even regress to presets in the first place? If i recall correctly, that one was implemented as a color picker prior to versions 3.0, when simple thank you was introduced, right?

[On medium.com](https://medium.com/@tibbi/5-million-downloads-on-2nd-anniversary-what-now-df7a31ff08a1), you did outline why the app icon got limited to preset colors, but the primary color does not have that constraint, right? Could it be rolled back to the picker?

**Comment by tibbi** [comment]
Some elements cannot be changed dynamically, I had to create preset themes and just pick from those. The limitation on primary color hasnt been there previously, but some elements remained orange after picking a color, so I limited it like this.

**Comment by SebiderSushi** [comment]
Thank you for this explanation.

Do you think adding a third action button to the "Primary color" selector would be an option?
What i'm thinking of here is changing the selector dialog to have "Customize", "Cancel" and "OK" as action buttons instead of just  "Cancel" and "OK. If "Customize" is clicked, the user will be instructed by a disclaimer, outlining that some elements cannot be customized at run time and that they will fall back to the color selected in the color picker. Accepting the disclaimer would then take the user to the manual color picker.

That way, any future theme like the one requested here could easily be implemented with a little compromise that will likely be acceptable to most people, while any other user won't be bothered by the change, as it would only be one additional button to them that can easily be ignored.

I'd be very happy if you are willing and able to implement this, as i'm a big fan of generic features.

**Comment by tibbi** [comment]
I dont want to add such buttons now, we will see in the future

**Comment by tibbi** [comment]
preset themes will be replaces by Material You in the future, so Ill close this
