### ISSUE TITLE
GPL3 and the sell

### ISSUE THREAD

**Issue by 0verEngineer** [SimpleMobileTools/General-Discussion#243]
Quote of @tibbi in the closed issue: `While I appreciate everyones contribution, you should know that like 99% of the current code has been written by me and other paid devs, so no need to overreact the licensing thing...`

You cannot sell code you do not own and **99% is not 100%**...

If i open some projects like the gallery or the file-manager then i can see a lot of contributors, you will need the permission of them to sell their code.

I understand that you do not want to accept it, but if you sold with something like "I have sole ownership of these apps / the code" and with no Mention that the Code is GPL3 Protected and not fully yours you could/will be in trouble.

I write this because you showed in the other issue that you do not understand how GPL works at all so the chance is quite high imho that you have a statement like "I have sole ownership of these apps / the code" in the contract.

And a possible GPL violation is has **nothing to do with overreacting**, this is simple, you do not fully own this code so you cannot sell it.

Feel free to close this issue, i just wanted to point it out again

**Comment by Aga-C** [comment]
There are e.g. my contributions that I did absolutely on my own without any formal agreement with Tibor. Also, there were some people who were translating the project via Weblate - I suppose most of them were working like me.

**Comment by Mr-Bajs** [comment]
Yup, noone asked med about the translations contrib that goes under the license? Hardly tibbor did all the 99% translations himself.

**Comment by Mr-Bajs** [comment]
i suppose it must suck for the main developer realising that the code is gplv3 and not a MIT, BSD license. Never heard of a case where a gpl license where relicensed under a closed source license.

**Comment by NLLAPPS** [comment]
I think there is a bit of confusion here. GPLv3 does not limit commercial activities. 

Author is publishing their source code and selling apps built by using the published source code. This is perfectly legal under GPLv3. Anyone can do that by using published source code. Anyone contributing to the project does so under same license. 

To me, it sounds like the author selling their Google Play Store presence, brand and user base which they have built over the years. This is perfectly legal under GPLv3 and has nothing to do with the license or source code of these apps. 

What required is that the new owners must publish source code of their derived work as soon as they make their derived work public by selling it or releasing it in any form, source, binary, whatever. It would then invoke the GPL requirement for release of the source.

**Comment by 0verEngineer** [comment]
@NLLAPPS Ther is no confusion here, if you read the other issue it sounds like the dev does not know how the gpl works. And i clearly say above IF he sold the code, claiming he owns 100% of the code he is in trouble because he does not own the full code.

If the sell takes into account that the code is gpl protected (with i doubt because the dev does not know how gpl works) then he is safe and it is zipoapps problem.

**Comment by NLLAPPS** [comment]
@0verEngineer he can definitely sell the code under GPLv3 whether s/he/they own(s) it or not. You can take this repo and sell it if you find some one to pay for it. There is no limitation on such activities. 

What required is that the new owners must publish source code of their derived work as soon as they make their derived work public by selling it or releasing it in any form, source, binary, whatever. It would then invoke the GPL requirement for release of the source.

**Comment by 0verEngineer** [comment]
@NLLAPPS You are right, he can sell it under the gpl, i have never said he cannot. But he cannot sell it like i explained above (claiming he owns 100% of the code and give the buyer all rights, also the right to change the license), because he does not own 100% of the code and it all comes down to how the sell contract is written.

Please stop the discussion now, this is not a discussion issue, i just want @tibbi to be aware that he might have legal problems.

**Comment by NLLAPPS** [comment]
GPLv3 allows alternative licensing. Author can provide alternative closed source license to buyer. This of course would require consent from other contributors . Perhaps they can remove contributions from other authors and sell under alternative license. I don't know specifics of such case.

It would have been a lot simpler if project had required a contributor license agreement (CLA) or copyright assignment from all contributors.

**Comment by 0verEngineer** [comment]
@NLLAPPS Yes as already written 20 times in the other issue. But the dev does not have an agreement from all the contributors and THIS IS NOT A DISCUSSION ABOUT THAT. 

I only wanted to make it clear to the dev that he will probably need a lawyer based on HOW THE CONTRACT IS WRITTEN.

**Comment by dengste** [comment]
Just a data point for SimpleGallery: according to git blame, Tibor has written 97.7% of lines. There are 148 contributors who have written 10 lines or more, which usually is enough to be considered "copyrightable".  49 people have contributed more than 100 lines.

Since this is purely based on git blame, there are of course lots of caveats: Tibor could have moved/refactored stuff by other people and vice versa, the lines might not be actual code but anything else which might not be enough for assuming copyright. This is why it is pretty much impossible to retroactively remove all foreign contributions for larger projects.

I don't think it makes much sense to discuss this further. By now, I think it is pretty clear that Tibor does not care, and most probably ZipoApps will neither, based on what I've read about this company. The sad truth is that this will most probably have zero legal consequences for both parties (if the sale goes through).

**Comment by bohwaz** [comment]
I just opened a Paypal claim asking for refund of our donation to Tibor, as we didn't provide funds towards a closed source project.

**Comment by hobbes** [comment]
> By now, I think it is pretty clear that Tibor does not care, and most probably ZipoApps will neither, based on what I've read about this company. The sad truth is that this will most probably have zero legal consequences for both parties (if the sale goes through).

no consequence ? As soon as zippo publishes the new apps, if they are closed source, each and every contributor to this project can file a DMCA claim with google: 

https://support.google.com/legal/troubleshooter/1114905#ts=1115643

The process is very simple, doesn't need lots of proofs, and will result in the app being banned from the playstore.

Then it's up to zippo to prove that they have all the rights to the apps, which they can't since they don't.  

Of course don't do this if you cannot prove later on that you do have rights to that code, the process is simple but you'll have to be able to prove copyright ownership when zippo claims that they have the rights.

**Comment by hobbes** [comment]
you might also want to contact the FSF, they have a team devoted to copyright compliance. They can't fight for compliance when they don't own the rights, but they do offer counsel. https://www.fsf.org/licensing/

« The FSF can only enforce the license on works to which we hold the copyright, but we can still help bring about compliance even when the copyright lies elsewhere. If you need help with enforcement, please don’t hesitate to contact us at license-violation@gnu.org. »

**Comment by dengste** [comment]
I explicitly wrote legal(!) consequence. Taking either party to court would be a big, expensive undertaking, which can only be done by an actual contributor who can claim copyright to parts of the code.

Contributors can of course file a DMCA, which will usually be just met with a counter notice. Pretty sure ZipoApps is used to these kind of things.

I'm guessing we're all not lawyers here, so in the end, your guess is as good as mine. Let's agree that it's just sad that someone would throw away something he worked so hard on, and his reputation, for a quick buck.

**Comment by zb3** [comment]
If I were ZipoApps I'd publish the code including the code that takes these apps To The Next Level, because it doesn't matter if it's Open Source or not. What matters is that users that installed these apps via Google Play will be shown ads, and that means $$$. F-Droid users or users who even know what GitHub is are not even financially relevant here, they won't generate leads anyway.
Alternatively I'd ask ChatGPT to rewrite the code by external contributors.

**Comment by x011** [comment]
Under the GPL license, if you have received contributions from others and you wish to change the license of the project, you typically need the agreement of all the contributors who hold copyright in their contributions. This is because the GPL license is a copyleft license, which means that when someone contributes to a GPL-licensed project, they are agreeing to distribute their contributions under the same license terms.

Changing the license of the project without the agreement of all the contributors would be a violation of their copyright and the GPL license terms. Each contributor has the right to decide under which terms they want their contributions to be distributed.

It is important to consult a legal professional or refer to the specific terms of the GPL license to fully understand your obligations and the requirements for changing the license of a GPL-licensed project.

**Comment by TheCoolRock64** [comment]
this is a terrible thing to happen.

**Comment by mutageneral** [comment]
> If I were ZipoApps I'd publish the code including the code that takes these apps To The Next Level, because it doesn't matter if it's Open Source or not. What matters is that users that installed these apps via Google Play will be shown ads, and that means $$$. F-Droid users or users who even know what GitHub is are not even financially relevant here, they won't generate leads anyway.

This is very true and was my exact thought when I heard of this, but the GPL does not allow adding proprietary software to the codebase, like an ad library. If the ad library was FOSS, then they could do this, but the chance of them switching to a FOSS ad library just for this is close to zero.

**Comment by Z0pyrus** [comment]
Has a contributor issued an DMCA notice?

**Comment by pastk** [comment]
> Has a contributor issued an DMCA notice?

I understand there is no legal ground to do it (yet).
The new owner didn't release any new app version while keeping the sources closed.
Also when/if it happens a contributor needs to be sure somehow that their code was not removed/rewritten by the new owner.

BTW [Software Freedom Conservancy](https://sfconservancy.org/) might help with the lawsuit and counsel.

**Comment by ikanakova** [comment]
There are hidden things in the apps to make it harder for fork developers, see https://github.com/FossifyOrg/Gallery/issues/73
GPL3 LOL.
