### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by beriain** [SimpleMobileTools/General-Discussion#3]
Hi! First of all, I want to thank you for your work. Your apps are great, simple and the most important (for me at least), with just the minimun necessary permissions.

I would want to translate the apps to basque and spanish, but they are 10, and forking all the projects and then merging the changes back takes some time.

Have you thought about using a translating platform such as [POEditor](https://poeditor.com/), [Weblate](https://weblate.org/) or [Transifex](https://www.transifex.com/) for example?

That way it would be quite easier for anyone to translate the apps.

Thank you again for your time.

**Comment by tibbi** [comment]
Hey, thanks for the feedback :)

The apps are still just in quite early development and multiple languages slow it down, so I dont really want to really propagate translation. It would take time to keep contacting the translators at every new string or existing string edit, so I usually just put the english strings into the already translated languages. External translation tools are really out of the question even more. 

If you want to translate into a new language or edit anything, there are a lot of helpful tools on Github which can help with it, if you are signed in. For example if you want to add a new language into the camera, just go to https://github.com/SimpleMobileTools/Simple-Camera/tree/master/app/src/main/res , at the top right corner you have a button "Create new file". There you can name the file like "values-xx/strings.xml", copy the content of strings.xml file from some existing language (preferably not english as that contains the non translatable strings too), at the bottom select "Create a new branch and pull request...", name it somehow and submit it. No messing around with git is needed.

I might see some things differently as Im an admin of these repos, but it should still be doable ;) I might publish these steps somewhere, proposing edits is a lot simpler than people think.

**Comment by tibbi** [comment]
Ive put together a FAQ, hope it makes sense and its not scarily long :p

**Comment by beriain** [comment]
Ok, I see your point. I didn't know that way of creating files but it really sounds quite easier and faster. I will give it a try for sure :)

However, in case you change your mind in the future, I think is worth mentioning that kind of translation platforms have some useful features, like filtering the untranslated or changed strings, so you can avoid the part of contacting the translators for example.

Thanks again and have a nice day

**Comment by mcbaze** [comment]
Hi! Thank you for the apps.

Is it annoying to apply commits to translations every time you add new value? I ask it because a translation should give non-english speaking pepole an ability to try some new cool features right after release. If i have enoug time to see that you have just added something, i'll translate and post commit.

So the question is: how often should i inerrupt (i really shouldn't) your work to be sure that release will contain all necessary translations?

**Comment by tibbi** [comment]
Well, you can click on the Code tab at the particular repository and check the commits, like at https://github.com/SimpleMobileTools/Simple-Gallery/commits/master . If you see that there are some recent commits, it means that Im working on it and it probably doesnt make much sense to translate anything, as it could change. If theres nothing being done in a couple hours, it will probably stay like that and you can translate.

I usually publish new versions of the apps as soon as Im done with something, so there will always be some untranslated new things. Waiting for translations would delay everything too much.

**Comment by mcbaze** [comment]
Ok, it's clear for me now. Thank you

**Comment by tibbi** [comment]
Also if I update the app version and the changelog, it means that Im releasing a new version and nothing more will be changing :)

**Comment by mueller-ma** [comment]
@tibbi Is it possible that all apps use the same strings.xml file? It would be easier than translation the same string in every repo

**Comment by tibbi** [comment]
then I would have to main 10 files :) Im already working on a new library Simple Commons, with which I want to avoid duplicating code and translations. It will contain hopefully all strings that are used in more than 1 app. Its currently at https://github.com/SimpleMobileTools/Simple-Commons/blob/master/library/src/main/res/values/strings.xml

**Comment by mueller-ma** [comment]
@tibbi What happens, when one string is different translated in Commons and e.g. Notes?

**Comment by tibbi** [comment]
strings that are in common will be removed from Notes and all other apps, I was just waiting for my library to get approved. Ill be doing it during this week

**Comment by mueller-ma** [comment]
@tibbi about german translations: In german have two words for "you". (see: http://www.dw.com/en/the-du-sie-dilemma-in-german/a-16494631). TLDR: One version is more polite ("sie") than the other ("du"). To stranger, older people, your boss, etc, you use the polite one, it can be a sign of disrespect not to do. However I like the "du" better in foss apps, because they are from a community and not from a company (the german wikipedia community also uses "du").

Until now I used "du", but I think you should know about this "problem"

**Comment by tibbi** [comment]
well okay thanks, I dont know the general experience, so do as you wish :)

**Comment by tibbi** [comment]
Anyone here actually has experience with setting up some translation service? Im trying Crowdin, but can't make it work. I mean some service that has Github integration so that I don't have to copypaste any files.

**Comment by Aga-C** [comment]
I haven't configured it, but maybe you should try Weblate? It integrates seamlessly with GitHub and handles Android strings without any problems. And also it's much better than Crowdin - fully open source, free for FLOSS projects, without any trackers on a site. Weblate works even without logging in - guest users can send translation suggestions for registered users.

However, I think that translating via GitHub is better since you have full control over the translations. On translation sites, there are often random people that translates horribly. Here you can be sure, that people who are translating in fact know the apps.

**Comment by tibbi** [comment]
everyone says that their integration is easy :) Ill take a look at it. It will work similarly, the translation service will just create a pull request that I still have to accept, I dont think the quality would differ. At least it will show the translation progress or untranslated things nicer.

**Comment by tibbi** [comment]
so I created a project with all apps on Weblate, you can check it at https://hosted.weblate.org/projects/simple-mobile-tools . We will see how will it work out.

**Comment by Aga-C** [comment]
@tibbi I saw that some source strings are changed again. In Weblate, there should be an option to block changing English strings - for example, F-Droid have them blocked. They are marked as `read-only strings`.
Also, SMS Messenger has blocked translations due to merge conflict. Can you solve it?

**Comment by tibbi** [comment]
ye I noticed that some english ones were translated too, will take a look at how to block them. Cleaned and accepted the SMS strings.

**Comment by Aga-C** [comment]
@tibbi Commons have translations blocked because after translating a new added string, in the same time another string was added, and it creates a conflict in one of translation files. Can you solve it? :) 
Typically, projects on Weblate add new strings only for source, English language, so there isn't then a problem, but I know your point, so in that case it would be good to check the state on Weblate each time after adding a new string.

**Comment by tibbi** [comment]
I solved a conflict some time ago. I will merge all translations from time to time, dont want to keep checking weblate for now

**Comment by Aga-C** [comment]
Unfortunately, it's still blocked.

![image](https://user-images.githubusercontent.com/85929121/142239695-1bc1582b-33b7-49fc-bb0c-a065b38e3597.png)
