### ISSUE TITLE
[New app idea] Simple Mail

### ISSUE THREAD

**Issue by Pofilo** [SimpleMobileTools/General-Discussion#89]
A simple IMAP client would be an excellent idea.

Maybe someone knows a simple IMAP client that does the job ?

**Comment by nigel12341** [comment]
agreed

**Comment by FTno** [comment]
I have been looking for an email checker for a while and have still not found any. There seem to be only large and heavy email clients.
With an email checker I mean an app that only download the headers initially and an entire message in plain text when it is to be viewed (and html and attachments only when the user explicitly choose to do so), and that doesn't store any messages on the phone.

**Comment by alaricljs** [comment]
K-9 Mail is my Android IMAP client of choice.  Like Simple apps, it's an open source effort:  https://k9mail.github.io/

**Comment by ltGuillaume** [comment]
I'd say, no need. For example, LineageOS still has a fine e-mail client you could extract and use. Otherwise:

https://f-droid.org/en/packages/eu.faircode.email/ which has a fork https://f-droid.org/en/packages/org.dystopia.email/ with more features (than the FairEmail free version)

https://f-droid.org/en/packages/com.fsck.k9/ which has a (possibly stale) fork https://f-droid.org/en/packages/com.fsck.k9.material/ with material design.

**Comment by stodge** [comment]
I'd still like to see a Simple Mail Client. I like the features and UI of these apps; a lot of people just need the basics. I use FairMail but its UI drives me nuts at times.

**Comment by ltGuillaume** [comment]
K-9 Mail development has been picked up with releases every few days and FairEmail is still the best you can get anywhere. A mail client is extremely complex, if tibbi would choose to create one, don't expect anything remotely usable for years. If you really want a non-nonsense mail client, you can try the email client from a LineageOS package matching your OS version.

**Comment by tibbi** [comment]
No, I definitely wont work on it as it doesnt suit the other apps at all. It is far from being simple and cannot work offline. Ill even close this, thanks.
